[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = https://gtazjqrjaeqpewudhmff.supabase.co
  NEXT_PUBLIC_SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YXpqcXJqYWVxcGV3dWRobWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwMzg3MTIsImV4cCI6MjA3NTYxNDcxMn0.JybAlawhmdAFBcnHqj_wu9UbA4JgqM9RGZjQhAhR7FU

[[plugins]]
  package = "@netlify/plugin-nextjs"
